
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.text.PlainDocument;

import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Litesav
 */
public class mainFrame extends javax.swing.JFrame {
	static double min = 0;
	public static List<String> list = new ArrayList<>();
	public static  JList jList1 = new javax.swing.JList<>();
    /**
     * Creates new form mainFrame
     * @throws IOException 
     */
    public mainFrame() throws IOException {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
       JLabel jLabel1 = new javax.swing.JLabel();
       JLabel jLabel2 = new javax.swing.JLabel();
       JLabel jLabel3 = new javax.swing.JLabel();
       JLabel jLabel4 = new javax.swing.JLabel();
       JLabel jLabel5 = new javax.swing.JLabel();
       JLabel jLabel6 = new javax.swing.JLabel();
       JLabel jLabel7 = new javax.swing.JLabel();
       JLabel jLabel8 = new javax.swing.JLabel();
       JLabel soot = new javax.swing.JLabel();
       JCheckBox work = new javax.swing.JCheckBox();
       JCheckBox work1 = new javax.swing.JCheckBox();
       JCheckBox work2 = new javax.swing.JCheckBox();
       JCheckBox work3 = new javax.swing.JCheckBox();
       JSeparator jSeparator1 = new javax.swing.JSeparator();
       JSeparator jSeparator2 = new javax.swing.JSeparator();
       JCheckBox jCheckBox1 = new javax.swing.JCheckBox();
       JCheckBox jCheckBox2 = new javax.swing.JCheckBox();
       JLabel  jLabel9 = new javax.swing.JLabel();
       JTextField jTextField1 = new javax.swing.JTextField();
        JLabel jLabel10 = new javax.swing.JLabel();
        JLabel  jLabel11 = new javax.swing.JLabel();
        JSpinner jSpinner1 = new javax.swing.JSpinner();
        JCheckBox jCheckBox3 = new javax.swing.JCheckBox();
        JLabel jLabel12 = new javax.swing.JLabel();
        JTextField jTextField2 = new javax.swing.JTextField();
        JLabel  jLabel13 = new javax.swing.JLabel();
        JLabel jLabel14 = new javax.swing.JLabel();
        JTextField jTextField3 = new javax.swing.JTextField();
        JLabel jLabel15 = new javax.swing.JLabel();
        JSpinner jSpinner2 = new javax.swing.JSpinner();
        JLabel  jLabel16 = new javax.swing.JLabel();
        JLabel jLabel17 = new javax.swing.JLabel();
        JTextField jTextField4 = new javax.swing.JTextField();
        JLabel jLabel18 = new javax.swing.JLabel();
        JLabel jLabel19 = new javax.swing.JLabel();
        JLabel jLabel20 = new javax.swing.JLabel();
        JLabel jLabel21 = new javax.swing.JLabel();
        JLabel jLabel22 = new javax.swing.JLabel();
        JLabel jLabel24 = new javax.swing.JLabel();
        JCheckBox jCheckBox5 = new javax.swing.JCheckBox();
        JCheckBox jCheckBox8 = new javax.swing.JCheckBox();
        JCheckBox jCheckBox9 = new javax.swing.JCheckBox();
        JCheckBox jCheckBox10 = new javax.swing.JCheckBox();
        JToolBar jToolBar1 = new javax.swing.JToolBar();
        JButton jButton1 = new javax.swing.JButton();
        JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jSeparator1 = new javax.swing.JSeparator();
        JLabel jLabel23 = new javax.swing.JLabel();
        JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        JMenu jMenu1 = new javax.swing.JMenu();
        JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        
        
    
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Статистический анализ выдачи займа.");
        setLocation(new java.awt.Point(0, 50));
        setPreferredSize(new Dimension(1400,650));
        HSSFSheet sheet = UploadFile.wbook.getSheetAt(0);
        
		Object[][] table = new Object[sheet.getLastRowNum()-1][sheet.getRow(0).getLastCellNum()];
		String[] name = new String[sheet.getRow(2).getLastCellNum()];
		
		for(int j = 0; j < 1; j++) {
			HSSFRow row = sheet.getRow(j);
			for(int i = 0; i < row.getLastCellNum(); i++) {
				HSSFCell cell = row.getCell(i);
				name[i] = cell.getRichStringCellValue().getString();
				}}
		
		for(int j = 1; j < sheet.getLastRowNum(); j++) {
		HSSFRow row = sheet.getRow(j);
		for(int i = 0; i < row.getLastCellNum(); i++) {
		HSSFCell cell = row.getCell(i);
		if (row.getCell(i) != null) {
		//System.out.print(cell.getCellType().toString() + " " + sheet.getLastRowNum() + " " + row.getLastCellNum() );
		if((cell.getCellType().toString() == "FORMULA")||(cell.getCellType().toString() == "NUMERIC")) {
		//System.out.print(cell.getNumericCellValue() + " ");
		table[j-1][i] = String.valueOf(cell.getNumericCellValue());}
		if(cell.getCellType().toString() == "STRING") {
		//System.out.print(cell.getRichStringCellValue().getString() + " ");	
		table[j-1][i] = cell.getRichStringCellValue().getString();}
		if((cell.getCellType().toString() == "FORMULA") && (j==1)) min = Double.valueOf(cell.getNumericCellValue());
		}
		}
	}
		//System.out.println("Первое значение " + min);
		int workon, por, sud, dolg, res, sootn, mrot;
		workon = 0; por = 0; sud = 0; dolg = 0; res = 0; sootn = 0; mrot = 0;
		for(int i = 0; i < name.length; i++) {
			if(name[i].equals("Результат"))   res = i;
			if(name[i].equals("Трудоустройство")) workon = i;
			if(name[i].equals("Наличие поручителя")) por = i;
			if(name[i].equals("Судимость")) sud = i;
			if(name[i].equals("Задолженности по кредиту")) dolg = i;
			if(name[i].equals("Соотношение")) sootn = i;
			if(name[i].equals("МРОТ")) mrot = i;
		}
		double sumMrot = Double.valueOf(table[0][mrot].toString());
		list.add("Сумма МРОТ определена как: " +sumMrot);
		updateList();
		//System.out.println(res + " " + workon + " " + por + " " + sud + " " + dolg + " " + sootn);
		//System.out.println(" из Object в Double "+ Double.valueOf(table[3][sootn].toString()));
		boolean workyes,poryes,sudyes,dolgyes;
		workyes = false;poryes = false; sudyes = false; dolgyes = false;
		for(int i = 0; i < sheet.getLastRowNum()-2; i++) {
			if(table[i][res].equals("Отказ") && (table[i][workon].equals("нет"))&&(table[i][por].equals("да")) && (table[i][sud].equals("нет")) && (table[i][dolg].equals("нет"))) {
				workyes = true;
				list.add("Комбинация(нет работы, отказ, др.факторы благоприятны) найдена на строке: " + table[i][0]);
				updateList();
			}
			if(table[i][res].equals("Отказ") && (table[i][por].equals("нет"))&&(table[i][workon].equals("есть")) && (table[i][sud].equals("нет")) && (table[i][dolg].equals("нет"))) {
				poryes = true;
				list.add("Комбинация(нет поручителя, отказ, др.факторы благоприятны) найдена на строке: " + table[i][0]);
				updateList();
			}
			if(table[i][res].equals("Отказ") && (table[i][sud].equals("да"))&&(table[i][workon].equals("есть")) && (table[i][por].equals("да")) && (table[i][dolg].equals("нет"))) {
				sudyes = true;
				list.add("Комбинация(есть судимость, отказ, др.факторы благоприятны) найдена на строке: " + table[i][0]);
				updateList();
			}
			if(table[i][res].equals("Отказ") && (!(table[i][dolg].equals("нет")))&&(table[i][workon].equals("есть")) && (table[i][por].equals("да")) && (table[i][sud].equals("нет"))) {
				dolgyes = true;
				list.add("Комбинация(есть задолженность, отказ, др.факторы благоприятны) найдена на строке: " + table[i][0]);
				updateList();
			}
			if((Double.valueOf(table[i][sootn].toString()) < min) && (table[i][res].equals("Принято"))) min = Double.valueOf(table[i][sootn].toString());
		}
		list.add("Минимальное соотношение при благоприятном результате определено как:" + min);
		updateList();
		
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            table, name
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(100, 640));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("На основании загруженных данных можно сделать вывод о необходимости соблюдения следующих факторов");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Первичные:");

        jLabel3.setText("Наличие трудоустройства:");

        jLabel4.setText("Наличие поручителя:");

        jLabel5.setText("Отсутствие судимости:");

        jLabel6.setText("Отсутствие задолженности по кредитам:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Вторичные:");

        jLabel8.setText("Минимальное соотношение U:");
        
        jLabel13.setText("т.р");
        
        jLabel24.setText("т.р");

        soot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        soot.setForeground(new java.awt.Color(0, 51, 204));
        soot.setText(String.valueOf(min));

       if(workyes) work.setSelected(true);
       else work.setSelected(false);//наличие трудоустройства
        work.setEnabled(false);
        
        if(poryes) work1.setSelected(true);
        else work1.setSelected(false);//наличие поручителя
        work1.setEnabled(false);
        
        if(sudyes) work2.setSelected(true);
        else work2.setSelected(false);// отсутствие судимости
        work2.setEnabled(false);

       if (dolgyes) work3.setSelected(true); 
       else work3.setSelected(false); //отсутствие задолженности по кредитам
       work3.setEnabled(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        
       // jCheckBox1.setEnabled(false);
        jCheckBox1.setVisible(false);
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("*обязательно к соблюдению");
        jCheckBox2.setEnabled(false);

        jLabel9.setText("Проверить результат одобрения новой заявки ");

        jLabel10.setText("Ф.И.О");

        jLabel11.setText("Возраст");

        jSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner1, ""));

        jCheckBox3.setText("Женат/Замужем");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jCheckBox3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Среднемесячный доход");

        jLabel13.setText("т.р");

        jLabel14.setText("Сумма займа");

        jLabel15.setText("Желаемый процент");

        jLabel16.setText("Семейное положение");

        jLabel17.setText("Срок выплаты");

        jLabel18.setText("мес.");

        jLabel19.setText("Наличие трудоустройства:");

        jLabel20.setText("Отсутствие задолженности:");

        jLabel21.setText("Наличие поручителя:");

        jLabel22.setText("Отсутствие судимости:");

        jToolBar1.setRollover(true);
        
        PlainDocument doc = (PlainDocument) jTextField2.getDocument();
        PlainDocument doc2 = (PlainDocument) jTextField3.getDocument();
        PlainDocument doc3 = (PlainDocument) jTextField4.getDocument();
        doc.setDocumentFilter(new DigitFilter());
        doc2.setDocumentFilter(new DigitFilter());
        doc3.setDocumentFilter(new DigitFilter());
        jTextField1.setText(""); //Ф.И.О
        jTextField2.setText(""); //Среднемесячный доход
        jTextField3.setText(""); //Сумма займа
        jTextField4.setText(""); //Срок выплаты
        jCheckBox5.setSelected(true); //Наличие трудоустройства
        jCheckBox8.setSelected(true); //Отсутствие задолженности
        jCheckBox9.setSelected(true); //Отсутствие судимости
        jCheckBox10.setSelected(true); //Наличие поручителя
        jSpinner1.setValue(18);
        jSpinner2.setValue(1);
       
        
        jButton1.setText("Проверить результат");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 if ((jTextField2.getText().isEmpty())||(jTextField3.getText().isEmpty())||(jTextField4.getText().isEmpty())) {
            		 final Runnable runnable =
                		     (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.hand");
                		if (runnable != null) runnable.run();
            		 JOptionPane.showMessageDialog(null, "Заполните все поля",  "Заполнение", JOptionPane.ERROR_MESSAGE);
            	 }
            	 else {
            	 if (Double.valueOf(jSpinner1.getValue().toString()) < 18) {
            		 final Runnable runnable =
                		     (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.hand");
                		if (runnable != null) runnable.run();
            		 JOptionPane.showMessageDialog(null, "Заемщик не достиг минимального возраста",  "Возраст", JOptionPane.ERROR_MESSAGE);
            	 }
            	 else {
            	 double doxod = Double.valueOf(jTextField2.getText());
                 double zaim = Double.valueOf(jTextField3.getText());
                 double srok = Double.valueOf(jTextField4.getText());
                 double prc = Double.valueOf(jSpinner2.getValue().toString());
                 double result = (doxod - (zaim*((prc/100)+1)/(srok*12)))/sumMrot;
                 System.out.println("result: " + result);
            	//System.out.println("doxod: " + doxod + " " + "zaim: " + zaim + " srok:" + srok + " " + "procent: " + prc);
            	if(((work.isSelected()&&jCheckBox5.isSelected()) || (!work.isSelected())) && (work1.isSelected()&&jCheckBox10.isSelected() || (!work1.isSelected())) && (work2.isSelected()&&jCheckBox9.isSelected() || (!work2.isSelected())) && (work3.isSelected()&&jCheckBox8.isSelected() || (!work3.isSelected())) && (result >= min)) {final Runnable runnable =
            		     (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
            		if (runnable != null) runnable.run();
            	JOptionPane.showMessageDialog(null, "Заявка будет одобрена",  "Статус", JOptionPane.INFORMATION_MESSAGE);}
            	else {
            		String str = "не определена"; 
            		boolean osn =(((work.isSelected()&&jCheckBox5.isSelected()) || (!work.isSelected())) && (work1.isSelected()&&jCheckBox10.isSelected() || (!work1.isSelected())) && (work2.isSelected()&&jCheckBox9.isSelected() || (!work2.isSelected())) && (work3.isSelected()&&jCheckBox8.isSelected() || (!work3.isSelected())));
            		if(!osn) str = "несоответствие основным требованиям";
            		if(result <= min) str = "неподходящее соотношение денежных характеристик";
            		if((result <= min)&&(!osn)) str = "все плохо";
            		 final Runnable runnable =
                		     (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.hand");
                		if (runnable != null) runnable.run();
                	JOptionPane.showMessageDialog(null, "Отказ в выдаче займа" + "\n" + "Причина: " + str,  "Статус", JOptionPane.ERROR_MESSAGE);
            	}
            }
            	 }
            }
        });
        
        jScrollPane1.setViewportView(jList1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel23.setText("Логи алгоритма");
        
        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Litesav\\Desktop\\Icon-Searcher-152760.png")); // NOI18N
        jMenu1.setText("Файл");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Litesav\\Desktop\\folder-open_16.png")); // NOI18N
        jMenuItem1.setText("Открыть");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadFile.run();
                setVisible(false);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Litesav\\Desktop\\logout.png")); // NOI18N
        jMenuItem2.setText("Выход");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVisible(false);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox2)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(work2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(work3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(work1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(work)))
                                                .addGap(154, 154, 154)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(soot))
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel23))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jCheckBox3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13))
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel18))
                                            .addComponent(jLabel17)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox10)
                                            .addComponent(jCheckBox9)
                                            .addComponent(jCheckBox8)
                                            .addComponent(jCheckBox5)))))
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton1))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(work))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(soot)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(work1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(work2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6))
                                            .addComponent(work3))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel11)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox3)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(59, 59, 59))))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void action() throws IOException {

                        
                        
    }

    
    public static void updateList() {
   	 jList1.setModel(new javax.swing.AbstractListModel<String>(){
        	String[] strings = list.toArray(new String[list.size()]); 
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
   }


    public static void run(){
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new mainFrame().setVisible(true);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration                   
}
