
	import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
	import javax.swing.JFileChooser;
	import javax.swing.JOptionPane;
	import java.io.File;
	import java.io.FileInputStream;
	import java.io.IOException;
	import javax.imageio.ImageIO;
	import javax.swing.ImageIcon;
	import javax.swing.JFrame;
	import javax.swing.JLabel;
	import javax.swing.filechooser.FileNameExtensionFilter;
	import javax.xml.parsers.DocumentBuilder;
	import javax.xml.parsers.DocumentBuilderFactory;
	import javax.xml.parsers.ParserConfigurationException;
	import javax.xml.transform.OutputKeys;
	import javax.xml.transform.Transformer;
	import javax.xml.transform.TransformerException;
	import javax.xml.transform.TransformerFactory;
	import javax.xml.transform.dom.DOMSource;
	import javax.xml.transform.stream.StreamResult;
	import org.apache.poi.hssf.usermodel.HSSFWorkbook;
	import org.apache.poi.poifs.filesystem.POIFSFileSystem;
	import org.w3c.dom.Document;
	import org.w3c.dom.Element;
	import org.w3c.dom.NamedNodeMap;
	import org.w3c.dom.Node;
	import org.w3c.dom.NodeList;
	import org.xml.sax.SAXException;


	public class UploadFile extends javax.swing.JFrame  {
	    public static File XLS, newFile;
	    public static String Path;
	    public static Document mainDocument;
	    public static HSSFWorkbook wbook;
	    
	       
	    
	   
	    public UploadFile()  {    
	      initComponents(); 
	      jLabel2.setVisible(false);
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("checked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jFileChooser2 = new javax.swing.JFileChooser();
	        jLabel2 = new javax.swing.JLabel();
	        label1 = new java.awt.Label();
	        
	        
	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setTitle("Выбор файла");
	        setAutoRequestFocus(false);
	        setBackground(javax.swing.UIManager.getDefaults().getColor("PasswordField.selectionBackground"));
	        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	        setLocation(new java.awt.Point(300, 150));
	        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
	        addWindowListener(new java.awt.event.WindowAdapter() {
	            public void windowActivated(java.awt.event.WindowEvent evt) {
	                formWindowActivated(evt);
	            }
	        });
	        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

	        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

	        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 30));

	        jFileChooser2.setDialogTitle("");
	        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jFileChooser2ActionPerformed(evt);
	            }
	        });
	        getContentPane().add(jFileChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 690, 380));
	        FileNameExtensionFilter filter = new FileNameExtensionFilter(
	            "Excel-файл", "xls");
	        jFileChooser2.setFileFilter(filter);

	        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
	        jLabel2.setText("Выбранный файл не является документом EXCEL");
	        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 330, 40));

	        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        label1.setForeground(new java.awt.Color(0, 153, 0));
	        label1.setText("Выберите Excel документ с историей заёмщиков");
	        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 310, -1));
	        label1.getAccessibleContext().setAccessibleName("");

	        getAccessibleContext().setAccessibleName("frame1");
	        getAccessibleContext().setAccessibleDescription("");

	        pack();
	        setLocationRelativeTo(null);
	    }// </editor-fold>                        

	    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {   
	       File fileXls = jFileChooser2.getSelectedFile();
	       Path = jFileChooser2.getSelectedFile().getAbsolutePath();
	        XLS = fileXls;
	        boolean validate = true;
	        try{
	        //проверка на xls
	        POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream(XLS));
		               HSSFWorkbook wb = new HSSFWorkbook(fs);
		               wbook = wb;
	                       
	        }
	        catch(Exception e){
	            System.out.println("Файл не подходит");
	            validate = false;
	        }
	        if(!validate){
	            jLabel2.setVisible(true);
	        }
	        else{
	            jLabel2.setVisible(false);
	            final Runnable runnable =
           		     (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
	            if (runnable != null) runnable.run();
	            JOptionPane.showMessageDialog(null, "Файл документа Excel успешно загружен",  "Проверка структуры", JOptionPane.INFORMATION_MESSAGE);
	        mainFrame.run();
	        this.setVisible(false);
	        jFileChooser2.setVisible(false);
	        
	        }
	    }                                             

	    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    /**
	     * @param args the command line arguments
	     */
	   
	     
	    public static void run() {

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run()  {
	                
	                new UploadFile().setVisible(true);}
	                
	            
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JFileChooser jFileChooser2;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private java.awt.Label label1;
	    // End of variables declaration                   
	}


